Repository swiftwave-org/dashboard, pull requests merged in 2023-10, with the labels that each got.

#43 fix: disabled fullchain textarea editing in SSL details
  src/components/SSLCertificateModal.jsx
Labels: bug, hacktoberfest, hacktoberfest-accepted

#45 feat: automatic refresh of the ingress and redirect rules page
  src/pages/ingress_rules.jsx
  src/pages/redirect_rules.jsx
  src/utils.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#53 feat: welcome action added
  .github/workflows/welcome.yml
Labels: hacktoberfest, hacktoberfest-accepted
